---
ansible_ssh_private_key_file: "~/.ssh/id_ed25519"

app_name: blog

db_password: "{{ pg_password | default('') }}"

uptime_ping_url: "{{ upmon_ping_url | default('') }}"
uptime_interval_minutes: 5

datadog_agent_major_version: 7

datadog_config:
  tags:
    - "project:{{ project_name }}"
    - "service:{{ app_service_tag }}"
    - "env:production"

datadog_checks:
  http_check:
    init_config:
    instances:
      - name: "{{ app_name }} on {{ inventory_hostname }}"
        url: "http://127.0.0.1:{{ app_port }}/"
        timeout: 5
        collect_response_time: true
        tags:
          - "service:{{ app_service_tag }}"
          - "project:{{ project_name }}"
