locals {
  ansible_dir = "${path.module}/../ansible"

  inventory = join("\n", concat(
    ["# Generated by Terraform. Do not edit by hand.", "[webservers]"],
    [
      for index, vm in yandex_compute_instance.web :
      "web${index + 1} ansible_host=${vm.network_interface.0.nat_ip_address}"
    ],
    ["", "[webservers:vars]", "ansible_user=ubuntu", ""],
  ))

  terraform_vars = <<-EOT
    ---
    # Generated by Terraform. Do not edit by hand.
    db_host: "${yandex_mdb_postgresql_cluster.this.host[0].fqdn}"
    app_url: "https://${var.domain_name}"
  EOT
}

resource "local_file" "inventory" {
  filename        = "${local.ansible_dir}/inventory.ini"
  content         = local.inventory
  file_permission = "0644"
}

resource "local_file" "terraform_vars" {
  filename        = "${local.ansible_dir}/group_vars/all/terraform.yml"
  content         = local.terraform_vars
  file_permission = "0644"
}
