locals {
  ansible_dir = "${path.module}/../ansible"

  inventory = join("\n", concat(
    ["# Generated by Terraform. Do not edit by hand.", "[webservers]"],
    [
      for index, vm in yandex_compute_instance.web :
      "web${index + 1} ansible_host=${vm.network_interface.0.nat_ip_address}"
    ],
    ["", "[webservers:vars]", "ansible_user=ubuntu", ""],
  ))

  terraform_vars = join("\n", [
    "---",
    "# Generated by Terraform. Do not edit by hand.",
    "# No secrets here: the database password comes from the vault.",
    yamlencode({
      app_url         = local.app_url
      app_port        = local.app_port
      app_service_tag = var.app_service_tag
      db_host         = yandex_mdb_postgresql_cluster.this.host[0].fqdn
      db_port         = local.db_port
      db_name         = yandex_mdb_postgresql_database.app.name
      db_user         = yandex_mdb_postgresql_user.app.name
    }),
  ])
}

resource "local_file" "inventory" {
  filename        = "${local.ansible_dir}/inventory.ini"
  content         = local.inventory
  file_permission = "0644"
}

resource "local_file" "terraform_vars" {
  filename        = "${local.ansible_dir}/group_vars/all/terraform.yml"
  content         = local.terraform_vars
  file_permission = "0644"
}
