---
ansible_user: ubuntu
ansible_ssh_private_key_file: "~/.ssh/id_ed25519"

app_name: blog
app_image: "irubinshtein/devops-for-developers-project-74:latest"
app_dir: /opt/blog
app_port: 80
app_container_port: 8080

db_port: 6432
db_name: app
db_user: app
db_password: "{{ lookup('env', 'TF_VAR_pg_password') }}"
